# -*- coding: utf-8 -*-
"""InLook Stock Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCh4nL3Z1NwJ9_cbad9fH-zw78tUmNI6
"""

# ==========================================================
# STOCK ANALYZER V2.0
# Explainable Investment Rating Engine
#
# Author: Cooper Southworth
# Version: 2.0
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install ta
import ta
!pip install colorama

from ta.momentum import RSIIndicator
from ta.trend import MACD

from colorama import init, Fore, Back, Style
init(autoreset=True)

# ==========================================================
# CONFIGURATION
# ==========================================================

BENCHMARK = "SPY"

TRADING_DAYS = 252

LOOKBACK = "2y"

MAX_SCORE = 100

FUNDAMENTAL_RULES = {

    "Revenue Growth":[
        (.20,10),
        (.10,8),
        (.05,6),
        (0,3)
    ],

    "Profit Margin":[
        (.25,10),
        (.15,8),
        (.05,5),
        (0,2)
    ],

    "Return on Equity":[
        (.20,10),
        (.15,8),
        (.10,6),
        (.05,3)
    ],

    "Earnings Growth":[
        (.20,10),
        (.10,8),
        (0,5)
    ],

    "Debt to Equity":[
        (0,10),
    ],

    "Current Ratio":[
        (2,10),
        (1.5,8),
        (1,5)
    ]

}

TECHNICAL_RULES = {

"Golden Cross":8,

"Above MA50":5,

"Above MA200":5,

"RSI":4,

"MACD":3

}

RISK_RULES = {

"Forward PE":5,

"Beta":5,

"Dividend Yield":5,

"Volatility":5,

"Sharpe Ratio":10,

"Max Drawdown":5

}

WEIGHTS = {

"Revenue Growth":1.4,

"Profit Margin":1.5,

"Return on Equity":1.8,

"Earnings Growth":1.6,

"Debt to Equity":1.2,

"Current Ratio":1.0,

"Golden Cross":1.2,

"Above MA50":0.8,

"Above MA200":1.0,

"RSI":0.8,

"MACD":0.7,

"Forward PE":1.0,

"Beta":1.0,

"Dividend Yield":0.7,

"Volatility":1.2,

"Sharpe Ratio":2.0,

"Max Drawdown":1.5

}

def score_metric(value, thresholds, reverse=False):

    if value is None:
        return 0

    if pd.isna(value):
        return 0

    if reverse:

        thresholds = sorted(thresholds,key=lambda x:x[0])

        for maximum,score in thresholds:

            if value <= maximum:
                return score

        return 0

    else:

        thresholds = sorted(thresholds,key=lambda x:x[0],reverse=True)

        for minimum,score in thresholds:

            if value >= minimum:
                return score

        return 0

def gauge(score,max_score=100,length=30):

    filled = int(score/max_score*length)

    empty = length-filled

    return "█"*filled+"░"*empty

def confidence_score(metrics):

    available = 0

    total = len(metrics)

    for value in metrics.values():

        if value is not None:

            if not pd.isna(value):

                available += 1

    confidence = available/total*100

    return confidence

def download_stock(ticker):

    stock = yf.Ticker(ticker)

    history = stock.history(period=LOOKBACK)

    if history.empty:

        raise ValueError("Ticker not found.")

    info = stock.info

    return stock,history,info

def download_benchmark():

    benchmark_df = yf.download(
        BENCHMARK,
        period=LOOKBACK,
        progress=False
    )

    # If MultiIndex columns are present, flatten them. For single ticker, yfinance can return (Metric, Ticker)
    if isinstance(benchmark_df.columns, pd.MultiIndex):
        # Assume the structure is (Metric, Ticker) and extract the Metric level
        benchmark_df.columns = benchmark_df.columns.get_level_values(0)

    # Prioritize 'Adj Close' as it's the most adjusted price.
    if 'Adj Close' in benchmark_df.columns:
        benchmark_df['Close'] = benchmark_df['Adj Close']
    elif 'Close' in benchmark_df.columns:
        # If 'Adj Close' is not there, use 'Close' which should already be correctly named
        pass
    elif 'close' in benchmark_df.columns:
        benchmark_df = benchmark_df.rename(columns={'close': 'Close'})
    else:
        # If neither 'Adj Close' nor 'Close' (or 'close') is found, raise an error.
        raise ValueError("Could not find 'Close' or 'Adj Close' column in benchmark data.")

    # Keep only the 'Close' column for simplicity in calculations.
    benchmark_df = benchmark_df[['Close']]

    # Sanity check: ensure 'Close' column is of numeric type
    if 'Close' in benchmark_df.columns:
        benchmark_df['Close'] = pd.to_numeric(benchmark_df['Close'], errors='coerce')
        benchmark_df = benchmark_df.dropna(subset=['Close']) # Drop rows where Close price couldn't be converted

    return benchmark_df

def calculate_indicators(history):

    history = history.copy()

    history["MA20"] = history["Close"].rolling(20).mean()

    history["MA50"] = history["Close"].rolling(50).mean()

    history["MA200"] = history["Close"].rolling(200).mean()

    rsi = RSIIndicator(history["Close"],window=14)

    history["RSI"] = rsi.rsi()

    macd = MACD(history["Close"])

    history["MACD"] = macd.macd()

    history["Signal"] = macd.macd_signal()

    history["Histogram"] = macd.macd_diff()

    return history

def calculate_risk(history):

    returns = history["Close"].pct_change().dropna()

    annual_return = returns.mean()*TRADING_DAYS

    volatility = returns.std()*np.sqrt(TRADING_DAYS)

    sharpe = annual_return/volatility if volatility !=0 else 0

    cumulative = (1+returns).cumprod()

    running_max = cumulative.cummax()

    drawdown = cumulative/running_max-1

    max_drawdown = drawdown.min()

    return {

        "Annual Return":annual_return,

        "Volatility":volatility,

        "Sharpe Ratio":sharpe,

        "Max Drawdown":max_drawdown

    }

def benchmark_statistics(stock_history,benchmark_history):

    stock = calculate_risk(stock_history)

    benchmark = calculate_risk(benchmark_history)

    comparison = {

        "Return Difference":
            stock["Annual Return"]-
            benchmark["Annual Return"],

        "Sharpe Difference":
            stock["Sharpe Ratio"]-
            benchmark["Sharpe Ratio"],

        "Volatility Difference":
            stock["Volatility"]-
            benchmark["Volatility"]

    }

    return stock,benchmark,comparison

def collect_metrics(info):

    metrics = {

        "Revenue Growth":
            info.get("revenueGrowth"),

        "Profit Margin":
            info.get("profitMargins"),

        "Return on Equity":
            info.get("returnOnEquity"),

        "Forward PE":
            info.get("forwardPE"),

        "Debt to Equity":
            info.get("debtToEquity"),

        "Beta":
            info.get("beta"),

        "Dividend Yield":
            info.get("dividendYield"),

        "Earnings Growth":
            info.get("earningsGrowth"),

        "Current Ratio":
            info.get("currentRatio"),

        "Market Cap":
            info.get("marketCap")

    }

    return metrics

def score_fundamentals(metrics):

    scores = {}

    scores["Revenue Growth"] = score_metric(
        metrics["Revenue Growth"],
        FUNDAMENTAL_RULES["Revenue Growth"]
    )

    scores["Profit Margin"] = score_metric(
        metrics["Profit Margin"],
        FUNDAMENTAL_RULES["Profit Margin"]
    )

    scores["Return on Equity"] = score_metric(
        metrics["Return on Equity"],
        FUNDAMENTAL_RULES["Return on Equity"]
    )

    scores["Earnings Growth"] = score_metric(
        metrics["Earnings Growth"],
        FUNDAMENTAL_RULES["Earnings Growth"]
    )

    debt = metrics["Debt to Equity"]

    if debt is None or pd.isna(debt):
        scores["Debt to Equity"] = 0

    elif debt < 30:
        scores["Debt to Equity"] = 10

    elif debt < 60:
        scores["Debt to Equity"] = 8

    elif debt < 100:
        scores["Debt to Equity"] = 5

    elif debt < 200:
        scores["Debt to Equity"] = 2

    else:
        scores["Debt to Equity"] = 0

    scores["Current Ratio"] = score_metric(
        metrics["Current Ratio"],
        FUNDAMENTAL_RULES["Current Ratio"]
    )

    return scores

def score_technicals(history):

    scores = {}

    price = history["Close"].iloc[-1]

    ma50 = history["MA50"].iloc[-1]

    ma200 = history["MA200"].iloc[-1]

    rsi = history["RSI"].iloc[-1]

    macd = history["MACD"].iloc[-1]

    signal = history["Signal"].iloc[-1]

    scores["Golden Cross"] = 8 if ma50 > ma200 else 0

    scores["Above MA50"] = 5 if price > ma50 else 0

    scores["Above MA200"] = 5 if price > ma200 else 0

    if 40 <= rsi <= 60:
        scores["RSI"] = 4

    elif 30 <= rsi < 40 or 60 < rsi <= 70:
        scores["RSI"] = 3

    elif rsi < 30:
        scores["RSI"] = 2

    else:
        scores["RSI"] = 0

    scores["MACD"] = 3 if macd > signal else 0

    return scores

def score_risk(metrics,risk):

    scores = {}

    pe = metrics["Forward PE"]

    if pe is None or pd.isna(pe):

        scores["Forward PE"] = 0

    elif 10 <= pe <= 20:
        scores["Forward PE"] = 5

    elif 20 < pe <= 30:
        scores["Forward PE"] = 4

    elif 30 < pe <= 40:
        scores["Forward PE"] = 2

    else:
        scores["Forward PE"] = 0

    beta = metrics["Beta"]

    if beta is None or pd.isna(beta):

        scores["Beta"] = 0

    elif beta < 1:
        scores["Beta"] = 5

    elif beta < 1.3:
        scores["Beta"] = 4

    elif beta < 1.8:
        scores["Beta"] = 2

    else:
        scores["Beta"] = 0

    dividend = metrics["Dividend Yield"]

    if dividend is None or pd.isna(dividend):

        scores["Dividend Yield"] = 0

    elif .02 <= dividend <= .05:
        scores["Dividend Yield"] = 5

    elif .01 <= dividend < .02:
        scores["Dividend Yield"] = 4

    elif dividend > 0:
        scores["Dividend Yield"] = 2

    else:
        scores["Dividend Yield"] = 0

    volatility = risk["Volatility"]

    if volatility < .20:
        scores["Volatility"] = 5

    elif volatility < .30:
        scores["Volatility"] = 4

    elif volatility < .40:
        scores["Volatility"] = 2

    else:
        scores["Volatility"] = 0

    sharpe = risk["Sharpe Ratio"]

    if sharpe > 2:
        scores["Sharpe Ratio"] = 10

    elif sharpe > 1.5:
        scores["Sharpe Ratio"] = 8

    elif sharpe > 1:
        scores["Sharpe Ratio"] = 5

    else:
        scores["Sharpe Ratio"] = 2

    drawdown = abs(risk["Max Drawdown"])

    if drawdown < .10:
        scores["Max Drawdown"] = 5

    elif drawdown < .20:
        scores["Max Drawdown"] = 4

    elif drawdown < .35:
        scores["Max Drawdown"] = 2

    else:
        scores["Max Drawdown"] = 0

    return scores

def score_dataframe(scores):

    df = pd.DataFrame({

        "Metric":list(scores.keys()),

        "Score":list(scores.values())

    })

    df["Weight"] = df["Metric"].map(WEIGHTS)

    df["Weighted Score"] = df["Score"] * df["Weight"]

    df["Max"] = 10

    return df

def weighted_total(df):

    weighted = df["Weighted Score"].sum()

    maximum = (df["Weight"]*10).sum()

    percentage = weighted/maximum*100

    return weighted,maximum,percentage

def investment_rating(score):

    if score >= 90:

        return "STRONG BUY"

    elif score >= 80:

        return "BUY"

    elif score >= 70:

        return "HOLD"

    elif score >= 60:

        return "WEAK HOLD"

    elif score >= 50:

        return "SELL"

    else:

        return "STRONG SELL"

def explain_scores(fund_df,tech_df,risk_df):

    df = pd.concat([

        fund_df,

        tech_df,

        risk_df

    ])

    strengths = df.sort_values(

        "Weighted Score",

        ascending=False

    ).head(5)

    weaknesses = df.sort_values(

        "Weighted Score"

    ).head(5)

    return strengths,weaknesses

def print_report(company,
                 recommendation,
                 confidence,
                 score,
                 strengths,
                 weaknesses,
                 comparison):

    print()

    print("="*65)

    print(company.upper())

    print("="*65)

    print()

    print(Fore.CYAN + gauge(score))

    print()

    print(Fore.YELLOW+f"Investment Score : {score:.1f}/100")

    print(Fore.GREEN+f"Recommendation   : {recommendation}")

    print(Fore.MAGENTA+f"Confidence       : {confidence:.1f}%")

    print()

    print("="*65)

    print("TOP STRENGTHS")

    print("="*65)

    for _,row in strengths.iterrows():

        print(f"✔ {row['Metric']:<25}{row['Score']}")

    print()

    print("="*65)

    print("TOP CONCERNS")

    print("="*65)

    for _,row in weaknesses.iterrows():

        print(f"✖ {row['Metric']:<25}{row['Score']}")

    print()

    print("="*65)

    print("BENCHMARK VS SPY")

    print("="*65)

    print(f"Annual Return Advantage : {comparison['Return Difference']:.2%}")

    print(f"Sharpe Difference       : {comparison['Sharpe Difference']:.2f}")

    print(f"Volatility Difference   : {comparison['Volatility Difference']:.2%}")

    print("="*65)

ticker = input("Ticker: ").upper().strip()

stock,history,info = download_stock(ticker)

benchmark = download_benchmark()

history = calculate_indicators(history)

risk = calculate_risk(history)

metrics = collect_metrics(info)

fundamental_scores = score_fundamentals(metrics)

technical_scores = score_technicals(history)

risk_scores = score_risk(metrics,risk)

fund_df = score_dataframe(fundamental_scores)

tech_df = score_dataframe(technical_scores)

risk_df = score_dataframe(risk_scores)

fund_score = weighted_total(fund_df)[2]

tech_score = weighted_total(tech_df)[2]

risk_score = weighted_total(risk_df)[2]

overall = (.60*fund_score)+(.25*tech_score)+(.15*risk_score)

recommendation = investment_rating(overall)

confidence = confidence_score(metrics)

stock_stats,spy_stats,comparison = benchmark_statistics(

    history,

    benchmark

)

strengths,weaknesses = explain_scores(

    fund_df,

    tech_df,

    risk_df

)

print_report(

    info.get("longName",ticker),

    recommendation,

    confidence,

    overall,

    strengths,

    weaknesses,

    comparison

)

from math import pi
def radar_chart(fundamental,
                technical,
                risk):

    categories = [

        "Fundamental",

        "Technical",

        "Risk"

    ]

    values = [

        fundamental,

        technical,

        risk

    ]

    values += values[:1]

    angles = [

        n/float(len(categories))*2*pi

        for n in range(len(categories))

    ]

    angles += angles[:1]

    plt.figure(figsize=(7,7))

    ax = plt.subplot(111,polar=True)

    ax.plot(

        angles,

        values,

        linewidth=3

    )

    ax.fill(

        angles,

        values,

        alpha=.25

    )

    ax.set_xticks(angles[:-1])

    ax.set_xticklabels(categories)

    ax.set_ylim(0,100)

    plt.title("Portfolio Score Radar")

    plt.show()

def benchmark_chart(stock,
                    benchmark):

    labels = [

        "Return",

        "Sharpe",

        "Volatility"

    ]

    stock_values = [

        stock["Annual Return"]*100,

        stock["Sharpe Ratio"],

        stock["Volatility"]*100

    ]

    benchmark_values = [

        benchmark["Annual Return"]*100,

        benchmark["Sharpe Ratio"],

        benchmark["Volatility"]*100

    ]

    x = np.arange(len(labels))

    width = .35

    plt.figure(figsize=(8,5))

    plt.bar(

        x-width/2,

        stock_values,

        width,

        label="Stock"

    )

    plt.bar(

        x+width/2,

        benchmark_values,

        width,

        label="SPY"

    )

    plt.xticks(x,labels)

    plt.ylabel("Value")

    plt.title("Benchmark Comparison")

    plt.legend()

    plt.show()

def category_chart(fund,
                   tech,
                   risk):

    plt.figure(figsize=(8,5))

    plt.bar(

        [

            "Fundamental",

            "Technical",

            "Risk"

        ],

        [

            fund,

            tech,

            risk

        ]

    )

    plt.ylim(0,100)

    plt.ylabel("Percent")

    plt.title("Category Scores")

    plt.show()

def price_chart(history,
                ticker):

    plt.figure(figsize=(15,6))

    plt.plot(

        history.index,

        history["Close"],

        label="Close"

    )

    plt.plot(

        history.index,

        history["MA20"],

        label="MA20"

    )

    plt.plot(

        history.index,

        history["MA50"],

        label="MA50"

    )

    plt.plot(

        history.index,

        history["MA200"],

        label="MA200"

    )

    plt.title(f"{ticker} Price History")

    plt.legend()

    plt.show()

def rsi_chart(history):

    plt.figure(figsize=(15,4))

    plt.plot(

        history.index,

        history["RSI"]

    )

    plt.axhline(

        70,

        linestyle="--"

    )

    plt.axhline(

        30,

        linestyle="--"

    )

    plt.ylim(0,100)

    plt.title("RSI")

    plt.show()

def print_dataframe(df,title):

    print()

    print("="*60)

    print(title)

    print("="*60)

    print(

        df.sort_values(

            "Weighted Score",

            ascending=False

        )

    )

    print()

def export_results(fund,
                   tech,
                   risk,
                   ticker):

    report = pd.concat(

        [

            fund,

            tech,

            risk

        ],

        ignore_index=True

    )

    report.to_csv(

        f"{ticker}_analysis.csv",

        index=False

    )

    print()

    print(

        Fore.GREEN+

        f"Saved {ticker}_analysis.csv"

    )

def analyst_summary(score,
                    confidence,
                    comparison):

    print()

    print("="*70)

    print("ANALYST SUMMARY")

    print("="*70)

    if score >= 85:

        print(

            Fore.GREEN+

            "Institutional quality investment."

        )

    elif score >= 70:

        print(

            Fore.YELLOW+

            "Good long-term opportunity."

        )

    elif score >= 55:

        print(

            Fore.YELLOW+

            "Mixed investment outlook."

        )

    else:

        print(

            Fore.RED+

            "High-risk investment."

        )

    print()

    print(

        f"Confidence Level : {confidence:.1f}%"

    )

    print()

    if comparison["Sharpe Difference"] > 0:

        print(

            "✓ Better risk-adjusted returns than SPY"

        )

    else:

        print(

            "✖ Worse risk-adjusted returns than SPY"

        )

    if comparison["Return Difference"] > 0:

        print(

            "✓ Outperforming SPY"

        )

    else:

        print(

            "✖ Underperforming SPY"

        )

    if comparison["Volatility Difference"] < 0:

        print(

            "✓ Less volatile than SPY"

        )

    else:

        print(

            "✖ More volatile than SPY"

        )

    print("="*70)

print_dataframe(

    fund_df,

    "FUNDAMENTALS"

)

print_dataframe(

    tech_df,

    "TECHNICALS"

)

print_dataframe(

    risk_df,

    "RISK"

)

price_chart(

    history,

    ticker

)

rsi_chart(

    history

)

category_chart(

    fund_score,

    tech_score,

    risk_score

)

benchmark_chart(

    stock_stats,

    spy_stats

)

radar_chart(

    fund_score,

    tech_score,

    risk_score

)

analyst_summary(

    overall,

    confidence,

    comparison

)

export_results(

    fund_df,

    tech_df,

    risk_df,

    ticker

)